### ISSUE TITLE
[FEATURE] 음성 데이터 Socket 수신 및 S3 저장 + AWS Transcribe 호출

### ISSUE THREAD

**Issue by choiyoorim** [Nuri-Capstone/backend#9]
## 🌴 작업 브랜치 
-`feature/#9`

## 💼 TASK 개요 
- 사용자 음성 데이터 처리 관련

## ✅ TODO 및 진행현황 
- [ ] 음성 데이터 Socket을 통해 수신하기 + 수신 후 간단하게 데이터 전송해보기 
       - binary 메세지 전송 방식으로
- [ ] 음성 데이터 S3에 저장 후 URL 받아오기
- [ ] URL 기준으로 Transcribe 호출하고 사용자한테 변환된 텍스트 보내주기

## 🚨 주의사항
- [ ] 서버 구조 변환 필수
